version: '3'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000" 
    env_file:
      - ./backend/src/.env
    network_mode: host

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    network_mode: host